### ISSUE TITLE
Graph (scatter) Not Redrawing Correctly When Updating Data  

### ISSUE THREAD

**Issue by AntonellaAntonini** [whawker/react-jsx-highcharts#157] opened 2018-09-24 22:45 UTC
#### Bug or Feature Request?
Bug

#### Description
Hi, I'm using the <ScatterSeries /> component, I have to highlight selected points. When I select points, others are removed from the graph.
The data (pointsSelected, pointsNoSelected) are updated correctly and are in the array, but are not drawn.
**I need to use react-jsx-highcharts 2.2.1 to not update React.**

#### Live demo demonstrating bug
const { pointsSeleccionados, pointsNoSeleccionados } = this.state;
return (
<HighchartsChart plotOptions={plotOptions}>
              <Chart height={300} width={600} zoomType="xy"
                     onSelection={this.handleSelection} />
              <XAxis  labels={{ rotation: -60 }}  id="xAxis" startOnTick={true} endOnTick={true}>
                <XAxis.Title> {this.state.titleX}</XAxis.Title>
              </XAxis>
              <YAxis visible={true} id="scatter" >
                <YAxis.Title> {this.state.titleY}</YAxis.Title>
                <ScatterSeries name="select" data={pointsNoSeleccionados}  id="seleccionados" color="rgba(255, 0, 0, .8)" />
                <ScatterSeries name="no select" data={pointsSeleccionados}  id="noseleccionados" color="rgba(30, 132, 73, .8)" />
              </YAxis>
            </HighchartsChart>
);

#### Versions
* React JSX Highcharts version: 2.2.1
* Highcharts version: 6.1.0
* React version: 15.3.2

**Comment by whawker** [comment] 2018-09-25 08:47
@AntonellaAntonini could you show how you're passing the `pointsSeleccionados` / `pointsNoSeleccionados` state into a series?

**Comment by AntonellaAntonini** [comment] 2018-09-25 10:08
<HighchartsChart plotOptions={plotOptions}>
              <Chart height={300} width={600} zoomType="xy"
                     onSelection={this.handleSelection}/>
              <XAxis  labels={{ rotation: -60 }}  id="xAxis" startOnTick={true} endOnTick={true}>
                <XAxis.Title> {this.state.titleX}</XAxis.Title>
              </XAxis>
              <YAxis visible={true} id="scatter" >
                <YAxis.Title> {this.state.titleY}</YAxis.Title>
                **<ScatterSeries name="select" data={pointsNoSeleccionados}  id="seleccionados" color="rgba(255, 0, 0, .8)" />
                <ScatterSeries name="no select" data={pointsSeleccionados}  id="noseleccionados" color="rgba(30, 132, 73, .8)" />**
              </YAxis>
            </HighchartsChart>

**Comment by AntonellaAntonini** [comment] 2018-09-25 10:12
`render () {
 const { pointsSeleccionados, pointsNoSeleccionados } = this.state;
  return (
   <HighchartsChart plotOptions={plotOptions}>
              <Chart height={300t} width={800} zoomType="xy"
                     onSelection={this.handleSelection}/>
              <XAxis  labels={{ rotation: -60 }}  id="xAxis" startOnTick={true} endOnTick={true}>
                <XAxis.Title> {this.state.titleX}</XAxis.Title>
              </XAxis>
              <YAxis visible={true} id="scatter" >
                <YAxis.Title> {this.state.titleY}</YAxis.Title>
                <ScatterSeries name="select" data={pointsNoSeleccionados}  id="seleccionados" color="rgba(255, 0, 0, .8)" />
                <ScatterSeries name="no select" data={pointsSeleccionados}  id="noseleccionados" color="rgba(30, 132, 73, .8)" />
              </YAxis>
            </HighchartsChart>
  );
}`

**Comment by AntonellaAntonini** [comment] 2018-09-26 09:48
Resolved! I updated the library and it worked correctly.
Another question, I need scatter plot 3d and rotate it with the mouse as the example of the web (of highcharts-3d). Someone implemented it?
Thank you!!

**Comment by AntonellaAntonini** [comment] 2018-09-26 09:48
Resolved! I updated the library and it worked correctly.
Another question, I need scatter plot 3d and rotate it with the mouse as the example of the web (of highcharts-3d). Someone implemented it?
Thank you!!

**Comment by AntonellaAntonini** [comment] 2018-09-26 09:56
https://www.highcharts.com/demo/3d-scatter-draggable

**Comment by whawker** [comment] 2018-09-26 09:58
It's not with the mouse, but the principles should be the same? https://whawker.github.io/react-jsx-highcharts/examples/3DChart/index.html

Stackblitz: https://stackblitz.com/github/whawker/react-jsx-highcharts-examples?file=src%2F3DChart%2F3DChart.js

**Comment by AntonellaAntonini** [comment] 2018-09-26 10:03
Yes, I saw it .
I do not know how to rotate it by dragging it with a mouse

**Comment by whawker** [comment] 2018-09-26 10:08
> Resolved! I updated the library and it worked correctly.

Did you update Highcharts library? Or React JSX Highcharts library?

> I do not know how to rotate it by dragging it with a mouse

I haven't done this before, but I can have a look at making a simple demo

**Comment by AntonellaAntonini** [comment] 2018-09-26 10:16
I updated "Highcharts", "react-jsx-highcharts" and "react" to the latest version.
Thanks! I wait your answer :)

**Comment by whawker** [comment] 2018-09-26 11:00
As the issue is resolved I'm closing this, but will still respond with a simple demo soon

**Closed by whawker** 2018-09-26 11:00 UTC
