### ISSUE TITLE
Unable to toggle tooltip visibility

### ISSUE THREAD

**Issue by louis269279** [whawker/react-jsx-highcharts#226] opened 2019-09-10 12:26 UTC
#### Description
There seems to be an issue with toggling tooltip visibility using the 'enabled' prop. I tried three separate options.
- Option 1: Pass tooltip as a prop to <HighchartsChart> wrapper directly. This does not work since componentDidUpdate in BaseChart.js only checks if 'plotOptions' changes, it does not check for the 'tooltip' prop.
- Option 2: Conditionally render <Tooltip> component. Not sure why this does not work.
- Option 3: Render <Tooltip> with the 'enabled' prop. Not sure why this does not work either.
In my opinion all three options should work.

#### Live demo demonstrating bug
https://stackblitz.com/edit/base-chart-example-8k117q?file=MyChart.js
(please uncomment/comment out the code as appropriate to reproduce with each option)

#### Versions (latest at current time)
* React JSX Highcharts version: 3.6.1
* Highcharts version: 7.2.0
* React version: 16.9

#### Workarounds found
- Interestingly option 3 works with Highcharts v6.2.0, something changed with v7? But I want to use the latest version of Highcharts.
- Also, if (~option 1 and option 2~) or (option 1 and option 3) are present it seems to work, but I don't know if this is intended.
- Of course there are other methods, e.g. setting classnames to hide DOM elements, etc but they seem hacky.

**Comment by anajavi** [comment] 2019-09-10 15:10
This can be reproduced with plain highcharts:
https://jsfiddle.net/qrtpefaj/

It seems to be caused by this line:
https://github.com/whawker/react-jsx-highcharts/blob/a1a18821c5a18af9b6e0adb04e6c11ea0a38fd52/packages/react-jsx-highcharts/src/components/Tooltip/Tooltip.js#L26-L29

As removing it from plain highcharts version makes the tooltip work again.

I don't know if those lines are actually needed.

**Comment by anajavi** [comment] 2019-09-10 15:16
I think this can be fixed by changing https://github.com/whawker/react-jsx-highcharts/blob/a1a18821c5a18af9b6e0adb04e6c11ea0a38fd52/packages/react-jsx-highcharts/src/components/Tooltip/Tooltip.js#L46-L48

to:
```javascript
chart.tooltip.update(config, false);
```

At least that works in jsfiddle.

**Comment by anajavi** [comment] 2019-09-10 16:28
I made a PR that should fix options 2 and 3.

**Comment by anajavi** [comment] 2019-09-27 19:44
This should be fixed in react-jsx-highcharts@4.0.0-alpha.1 if you want to try that.

Updated stackblitz: https://stackblitz.com/edit/base-chart-example-8wi8m5?file=MyChart.js

**Closed** 2019-10-01 18:44 UTC
Labels: bug
