### ISSUE TITLE
Tooltip pointFormat not updating

### ISSUE THREAD

**Issue by louis269279** [whawker/react-jsx-highcharts#289] opened 2020-05-22 05:05 UTC
#### Bug or Feature Request?
Bug

#### Description
Unable to update tooltip format.

#### How to reproduce
1. Open stackblitz below.
2. Attempt to change pointFormat, with the button. The tooltip does not update

#### Live demo demonstrating bug
https://stackblitz.com/edit/base-chart-example-ko6uke?file=MyChart.js

#### Versions
* React JSX Highcharts version: 4.0.1
* Highcharts version: 8.1.0
* React version: 16.13.1

#### Notes
I believe this code works with an earlier version of highcharts + react-jsx-highcharts.

**Comment by anajavi** [comment] 2020-05-22 05:55
This is a regression in react-jsx-highcharts@4.

This works with react-jsx-highcharts@3.6.1 with highcharts@8.1.0.

**Comment by anajavi** [comment] 2020-05-22 06:20
This is probably caused by a fix for #226.

A fix for this should also check that #226 does not break again.

**Closed** 2020-06-04 18:10 UTC
Labels: bug
