### ISSUE TITLE
Series shadow options don't dynamically update

### ISSUE THREAD

**Issue by jhartling** [whawker/react-jsx-highcharts#232] opened 2019-09-27 21:02 UTC
#### Bug or Feature Request?
Bug

#### Description
Series shadow options aren't updated dynamically unless you disable / reenable the shadow.

#### How to reproduce
Try to update a series shadow color dynamically. It doesn't update until you toggle the shadow being enabled.

#### Live demo demonstrating bug
https://stackblitz.com/edit/base-chart-example-j7uwyh?file=MyChart.js

#### Versions
* React JSX Highcharts version: latest & next
* Highcharts version: 7.2.0
* React version: 16.9.0

**Comment by anajavi** [comment] 2019-09-28 06:13
Reproduction in pure Highcharts: https://jsfiddle.net/wnrq1tfy/1/

I created a issue in Highcharts repository: https://github.com/highcharts/highcharts/issues/12091

Waiting for Highcharts to fix this.

**Comment by anajavi** [comment] 2020-04-08 11:10
As the issue is already closed in highcharts repository this might be fixed in the next version of highcharts.

**Comment by anajavi** [comment] 2020-05-06 10:26
This is fixed in highcharts@8.1.0

**Closed by anajavi** 2020-05-06 10:26 UTC
Labels: needs Highcharts fix
